namespace Finance.Accounts.Core.Types
{
    public class SortCodeRecord
    {
        public string GENERALSortingCode { get; set; }
        public string GENERALBIC1 { get; set; }
        public string GENERALBIC2 { get; set; }
        public string GENERALSubBranchSuffix { get; set; }
        public string GENERALShortBranchTitle { get; set; }
        public string GENERALShortNameOwningBank { get; set; }
        public string GENERALFullNameOwningBankLine1 { get; set; }
        public string GENERALFullNameOwningBankLine2 { get; set; }
        public string GENERALBankCodeOwningBank { get; set; }
        public string GENERALNationalCentralBankCountryCode { get; set; }
        public string GENERALSupervisoryBody { get; set; }
        public string GENERALDeletedDate { get; set; }
        public DateTime? GENERALDateofLastChange { get; set; }
        public string GENERALPrintIndicator { get; set; }
        public string BACSStatus { get; set; }
        public DateTime? BACSDateofLastChange { get; set; }
        public string BACSDateClosedInBACSClearing { get; set; }
        public string BACSRedirectionFromFlag { get; set; }
        public string BACSRedirectToSortcode { get; set; }
        public string BACSSettlementBank { get; set; }
        public string BACSSettlementSection { get; set; }
        public string BACSSettlementSubSectionRALBankCodeOwningBank { get; set; }
        public string BACSHandlingBank { get; set; }
        public string BACSHandlingBankStream { get; set; }
        public string BACSAccountsNumberedFlag { get; set; }
        public string BACSDDIVoucherFlag { get; set; }
        public string BACSTransactionsDisallowedDR { get; set; }
        public string BACSTransactionsDisallowedCR { get; set; }
        public string BACSTransactionsDisallowedCU { get; set; }
        public string BACSTransactionsDisallowedPR { get; set; }
        public string BACSTransactionsDisallowedBS { get; set; }
        public string BACSTransactionsDisallowedDV { get; set; }
        public string BACSTransactionsDisallowedAU { get; set; }
        public string BACSTransactionsDisallowedSpare1 { get; set; }
        public string BACSTransactionsDisallowedSpare2 { get; set; }
        public string BACSTransactionsDisallowedSpare3 { get; set; }
        public string BACSSpare1 { get; set; }
        public string CHAPSSTERLINGReturnIndicator { get; set; }
        public string CHAPSSTERLINGStatus { get; set; }
        public DateTime? CHAPSSTERLINGEffectiveDateOfLastChange { get; set; }
        public DateTime? CHAPSSTERLINGDateClosed { get; set; }
        public string CHAPSSTERLINGSettlementMember { get; set; }
        public string CHAPSSTERLINGRoutingBICField1 { get; set; }
        public string CHAPSSTERLINGRoutingBICField2 { get; set; }
        public string CHAPSEUROStatus { get; set; }
        public DateTime? CHAPSEUROEffectiveDateOfLastChange { get; set; }
        public DateTime? CHAPSEURODateClosed { get; set; }
        public string CHAPSEURORoutingBICField1 { get; set; }
        public string CHAPSEURORoutingBICField2 { get; set; }
        public string CHAPSEUROSettlementMember { get; set; }
        public string CHAPSEUROReturnIndicator { get; set; }
        public string CHAPSEUROSwiftData { get; set; }
        public string CHAPSEUROSpare1 { get; set; }
        public string CCCCStatus { get; set; }
        public DateTime? CCCCeffectiveDateofLastChange { get; set; }
        public string CCCCDateClosed { get; set; }
        public string CCCCSettlementBank { get; set; }
        public string CCCCDebitAgencySortingCode { get; set; }
        public string CCCCReturnIndicator { get; set; }
        public string CCCCGBNIIndicator { get; set; }
        public string FASTStatus { get; set; }
        public DateTime? FASTEffectiveDateofLastChange { get; set; }
        public DateTime? FASTDateClosed { get; set; }
        public string FASTRedirectFromFlag { get; set; }
        public string FASTRedirectToSortingCode { get; set; }
        public string FASTFPSSettlementBankConnectionType { get; set; }
        public string FASTPadding { get; set; }
        public string FASTFPSSettlementBankBankCode { get; set; }
        public string FASTHandlingBankConnectionType { get; set; }
        public string FASTPadding2 { get; set; }
        public string FASTHandlingBankBankCode { get; set; }
        public string FASTAccountsNumberedFlag { get; set; }
        public string FASTAgencyType { get; set; }
        public string FASTSpareField { get; set; }
        public string PRINTBranchTypeIndicator { get; set; }
        public string PRINTSortcodeOfMainBranch { get; set; }
        public string PRINTMajorLocationName { get; set; }
        public string PRINTMinorLocationName { get; set; }
        public string PRINTBranchNameOrPlace { get; set; }
        public string PRINTSecondEntryIndicator { get; set; }
        public string PRINTBranchNameForSecondEntry { get; set; }
        public string PRINTFullBranchTitlePart1 { get; set; }
        public string PRINTFullBranchTitlePart2 { get; set; }
        public string PRINTFullBranchTitlePart3 { get; set; }
        public string PRINTAddressLine1 { get; set; }
        public string PRINTAddressLine2 { get; set; }
        public string PRINTAddressLine3 { get; set; }
        public string PRINTAddressLine4 { get; set; }
        public string PRINTTown { get; set; }
        public string PRINTCounty { get; set; }
        public string PRINTPostcodeField1 { get; set; }
        public string PRINTPostcodeField2 { get; set; }
        public string PRINTTelephoneArea { get; set; }
        public string PRINTTelephoneNumber { get; set; }
        public string PRINTTelephone2Area { get; set; }
        public string PRINTTelephone2Number { get; set; }
    }
}
